### ISSUE TITLE
Allow accurate functions (astrometric, photometric error, vignetting) also to circular footprint

### ISSUE THREAD

**Issue by fedorets** [dirac-institute/survey_simulator_post_processing#105]
Also, make scenarios as modes which are switched on in PPConfig.ini.

E.g. : fast: no astrometric errors, no photometric errors, no vignetting
         precise: incl. astrometric errors, photometric errors, vignetting

Anything else?

**Comment by mschwamb** [comment]
This is two issues. We shouldn't combine them. I'm closing and splitting into two
