### ISSUE TITLE
Footprint filters (circular or full on detector calculations) should be applied like any other filter

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#106]
Currently if you do the circular filter none of the other filters are applied. The choice of footprint filter should not effect any of the filters applied. The other filters should applied once a footprint filter has been applied

**Comment by astronomerritt** [comment]
Otherwise, since "circle" isn't actually applying a footprint filter, the only way I can think of to solve this issue would be to do something like this:

```
if (configs['cameraModel'] == "circle"):
    pplogger.info('Applying detection efficiency threshold...')
    observations=PPFilterDetectionEfficiencyThreshold.PPFilterDetectionEfficiencyThreshold(observations,configs['SSPDetectionEfficiency'])

elif (configs['cameraModel'] == "footprint"):
    pplogger.info('Applying sensor footprint filter...')
    footprintf = PPFootprintFilter.Footprint(configs['footprintPath'])
    onSensor, detectorIDs = footprintf.applyFootprint(observations, filterpointing)

    observations=observations.iloc[onSensor]
    observations["detectorID"] = detectorIDs

    observations = observations.sort_index()
        
```

...which I can wrap up in a function easily enough so it behaves like all the other filters.

**Comment by mschwamb** [comment]
Yep. That's actually what I was thinking

**Comment by mschwamb** [comment]
Circle really means it fills approximately 90% of the circle to 1.75 degree radius -  https://survey-simulator-post-processing.readthedocs.io/en/latest/inputs.html#filters - see the figure.

**Comment by astronomerritt** [comment]
Oh, that's clearer! Sorry, didn't realise just how far the docs had come. Will have this done by the end of the day, making sure I don't break the pip install.

**Comment by mschwamb** [comment]
As @astronomerritt  pointed out in #115 fill factor is not being used at all and is supposed to be used in the circle footprint. So this is reopened to address that in this ticket
