### ISSUE TITLE
Remove testValue  from config file readin in and post processing config file generator

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#109]
`# Do not change, value for test assertion, should always be 1`

`testValue= 1`

Is in the config file. This is not used anywhere within the code. Having variables/config file parameters that are not being used and are not serving a clear purpose should be removed.  So let's remove this config file variable from read in and from the config file generator.

**Comment by fedorets** [comment]
Fixed py pull request #128
