### ISSUE TITLE
modify outputformat config file parameters to take an separatelyCSV option

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#110]
Currently in the config file we have:

# options [csv | sqlite3 | hdf5 ]
outputformat = csv

# write out CSV file each object separately
separatelyCSV = False 

These can be combined into one where outputfot would be csv | sqlite3 | hdf5|separatelycsv and separatelycsv would serve the same purpose as separatelyCSV = True and would reduce confusion since output format would be on variable.

- [ ] Remove separatelyCSV  variable from config file read in 
- [ ] Add option for separatelyCSV  in outputformat 
- [ ]  make change to config file generator code

**Comment by fedorets** [comment]
Fixed by pull request #129.

**Comment by mschwamb** [comment]
Pull request not merged
