### ISSUE TITLE
fill factor should only be added to config file and read in  if using circle footprint

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#115]
- [ ] PPConfigFileParser needs to check that if using circle that fill factor is specified otherwise crash gracefully with an error
- [ ] If fill factor is specified and its not that foot print we should put in a warning in the log file that this was specified but is being ignored
- [ ] makeConfigPP.py should not let you set the footprint to camera and add a fill factor

**Comment by astronomerritt** [comment]
Currently the circle footprint doesn't use the fillfactor parameter. In fact, I can't see that if the fillfactor parameter is used at all in the code. The application of the circle footprint uses the SSPDetectionEfficiency variable from the config file instead:

```       
if (configs['cameraModel'] == "circle"):
        pplogger.info('Applying detection efficiency threshold...')
        observations=PPFilterDetectionEfficiencyThreshold.PPFilterDetectionEfficiencyThreshold(observations,configs['SSPDetectionEfficiency'])
```

This was the case before I moved it into its own function, I didn't change the code at all.

**Comment by mschwamb** [comment]
observations=PPFilterDetectionEfficiencyThreshold.PPFilterDetectionEfficiencyThreshold(observations,configs['SSPDetectionEfficiency']) should be removed
        
So for now if it's circle - let's just have it log it is a circle and has set fill factor specified in the config value and  then in survesimPP modify the line
        
        

        
                pplogger.info('Calculating probabilities of detections...')
        observations["detection_probability"] = PPDetectionProbability(observations, filterpointing) 
        
        PPDetectionProbability deals with the fill factor and the call needs to be updated to use the config file value  and have the config file value and have the value set to one if using the camera footprint.

**Comment by mschwamb** [comment]
Thank you for catching this @astronomerritt  - I think I've figured it out in #115

**Comment by mschwamb** [comment]
observations=PPFilterDetectionEfficiencyThreshold.PPFilterDetectionEfficiencyThreshold(observations,configs['SSPDetectionEfficiency'])" 
  
  should be moved to surveysimPP above line 219.  It takes into account that SSP only links 95% of the detections 
 
I think PPFilterDetectionEfficiencyThreshold shouldn't be only applied to the circle FOV only. This needs to be checked, but  since it has nothing to with a circular footprint and the filling factor it shoudn't be in this FOV filter..

**Comment by astronomerritt** [comment]
Ah, okay. 

Does _anything_ need to be done if cameraModel=="circle"? Because if I move PPFilterDetectionEfficiencyThreshold out of PPApplyFOVFilter, then there's nothing in that if-statement.

**Comment by mschwamb** [comment]
Let's just have it log it is a circle and has set fill factor specified in the config value for now. We can change it later if needed. But probably good to have this logged anyway.
