### ISSUE TITLE
Update SSPP config file generator to add ephemerides_type=oif

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#117]
Currently the SSPP config file generator I wrote (makeConfigPP.py)  is missing the `ephemerides_type` variable, which was recently added.

This is likely to be a recurring issue as more and more things are added or changed in the config file.

**Comment by mschwamb** [comment]
@astronomerritt could we try to get all the easy config file changes in this week like this one?

**Comment by astronomerritt** [comment]
This is for the config file generator -- but yes, I am planning to have that updated by the end of the week!
