### ISSUE TITLE
Update SSPP config file generator to automatically generate several config files

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#118]
The SSPP config file generator I wrote (makeConfigPP.py) currently does not have the functionality to generate 100s of config files automatically in 100s of different directories. This is pretty vital functionality if the config file generator is used for its intended use of allowing many, many runs to be performed automatically on a supercomputer. Apparently the OIF config file generator does do this, so it should be a matter of comparing the two and adding the necessary functionality to makeConfigPP.py.

**Comment by mschwamb** [comment]
So we've agreed. That OIF should get split into and one can use one config file and different command line values in the slurm script.
