### ISSUE TITLE
Update and fix unit tests

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#134]
- [x] Fix unit tests so they run in the new setup for pip install
- [ ] Add unit tests for new functions that do not have unit tests

**Comment by mschwamb** [comment]
Thanks to @thespacedoctor  for making the unit tests work again

**Comment by astronomerritt** [comment]
I've gone through the code and made a list of good existing unit tests, bad existing unit tests, functions that don't have a unit test and need one, and priorities for unit tests. It's [here ](https://docs.google.com/document/d/1cRnCGi6FNPmIkI_4btTqWlz3_kUcAPQY1Q2SNGXHRhM/edit?usp=sharing) if anyone wants to look at it.
