### ISSUE TITLE
Tidy up PPConfigFileParser

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#170]
PPRunUtilities.PPConfigFileParser has gotten very long and unwieldy. I'm hoping to eventually tidy up a lot of it into its own individual functions for readability and possibly pop it into its own module. Not a high priority as yet.

- [ ] add proper type checking
- [ ] general tidy up

**Comment by astronomerritt** [comment]
This would include writing a function that performs type checking and boundary checking, as there's a lot of duplicate code in this function that does this.

**Comment by mschwamb** [comment]
I think the code is generally pretty tidy. It's long because there are lot of config variables, I think it's the type checking and setting flags in your dictionary that things exist will help.
