### ISSUE TITLE
SSPDetectionEfficiency config file variable not being used?

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#171]
I did a quick grep for it and it doesn't seem like the config file variable SSPDetectionEfficiency is being used anywhere. Is there any plan to implement this or should it be removed?

**Comment by mschwamb** [comment]
SSPDetectionEfficiency is the efficiency of actually linking detections. So 95% of detections will get successfully linked. PPFilterSSPCriterionEfficiency.py  should use it and the first step it in that function should be

PPFilterDetectionEfficiencyThreshold.PPFilterDetectionEfficiencyThreshold(observations, configs[' SSPDetectionEfficiency']))

Let's change PPFilterDetectionEfficiencyThreshold's name to PPDetectionEfficiency so it is much clearer what is doing.
