### ISSUE TITLE
Check that all values being read from config file are the right type

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#172]
Right now, if someone (for example) input a string (or somehting else that does not convert nicely to a float) for "brightLimit", it does not fail gracefully. I need to implement proper type checking.

**Comment by mschwamb** [comment]
Have a look at this:
```

import configparser

config = configparser.RawConfigParser()
config.read('example.cfg')

# getfloat() raises an exception if the value is not a float
# getint() and getboolean() also do this for their respective types
a_float = config.getfloat('Section1', 'a_float')
an_int = config.getint('Section1', 'an_int')
print(a_float + an_int)

https://docs.python.org/3/library/configparser.html

```

**Comment by astronomerritt** [comment]
...this is a lesson to me to double-check whether the module has the functionality I want _before_ I go and rewrite it. Thanks for the heads-up on this!
