### ISSUE TITLE
calculating fiveSigmaDepthAtSource

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#175]
We should calculate a fiveSigmaDepthAtSource. This is what will have the vignetting considerations applied. I think we have a new function that would have:

```
 pplogger.info('Calculating vignetting losses...')
       dmagVignet=PPVignetting.vignettingLosses(observations)

observations[fiveSigmaDepthAtSource]=fiveSigmaDepth- dmagVignet

```

The idea is that we calculate an effective limiting magnitude at the moving object's location and this would take vignetting into account. The vignetting makes the effective limiting magnitude occur at a brighter mag 

This requires that surveySimPP calls the function that calculates the fiveSigmaDepthAtSource and  take the old bit out of surveysimPP that was there before. 

Also 

https://github.com/dirac-institute/survey_simulator_post_processing/blob/b2ae928382e8e70b58d73314fd11bda3c2783c10/surveySimPP/surveySimPP.py#L133

would get modified removed the dmagVignet term and fiveSigmaDepth would be changed to fiveSigmaDepthAtSource

**Comment by astronomerritt** [comment]
Currently fiveSigmaDepth is being output in the final csv, and from [this post on Slack](https://qubsolarsystem.slack.com/archives/CQYN0CN00/p1647352485150209?thread_ts=1647350994.809689&cid=CQYN0CN00) I can see we actually do want to keep that in the final output. Do we want fiveSigmaDepthAtSource in the output as well?

**Comment by astronomerritt** [comment]
Disregard above question, apparently everything is being written to output currently...

**Comment by mschwamb** [comment]
yes
