### ISSUE TITLE
PPDetectionProbability probability needs to use fiveSigmaDepthAtSource and  PSFMag as defaults

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#179]
Because we're defining these new mags they need to be used in PPDetection Proability. That also means removing the trailing loss flag and having PSFMag set to be the same thing as TrailedSourceMag if trailing sources are off.

**Comment by astronomerritt** [comment]
Quick question: what do you mean by removing the trailing loss flag? I've just changed it so that if the flag is False then PSFMag = TrailedSourceMag.

**Comment by astronomerritt** [comment]
Also, to do this, I've moved PPDetectionProbability to be called _after_ vignetting and trailing losses are calculated, as these are the things that create PSFMag and fiveSigmaDepthAtSource. This makes sense to me. Let me know if it's wrong, though.

**Comment by mschwamb** [comment]
Yeah that ordering seems fine for now.
