### ISSUE TITLE
update config file parser functions to check if the variable is there without error trapping

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#193]
```

def PPGetOrExit(config, section, key, message):
    # from Shantanu Naidu, objectInField
    try:
        return config[section][key]
    except KeyError:
        logging.error(message)
        sys.exit(message)
        

def PPGetOrPass(config, section, key, message):
    # as PPGetOrExit, except if the config variable doesn't exist, returns 0
    # essentially turns off filters if the variable isn't given
    try:
        return config[section][key]
    except KeyError:
        logging.info(message)
        return 0
```

There is config.has_option() and config.get() that can do these checks and set default values:

see https://stackoverflow.com/questions/70845111/configparser-check-if-variable-in-config-file-exists

Let's update these functions to do this and set a value. My concern is that if you 0 what happens if I set the value to 0 for one of these config file variables. Would we know the difference based on what's written. Using has_option() means we put flags true if the value or false if the value is there or not.

**Comment by astronomerritt** [comment]
This is also great, thanks!
