### ISSUE TITLE
Parametrise the width parameter for the fading function

### ISSUE THREAD

**Issue by fedorets** [dirac-institute/survey_simulator_post_processing#223]
The width parameter for the fading function should be parametrised in the PPConfig file generator.

Following the notation of Veres and Chesley (2017):

$$\epsilon(m) = \frac{F}{1 + e^\frac{m-m_5}{w}}$$

where epsilon is the probability of detection, F is the fill factor, m and m5 are observed and 5sigma magnitudes, and w is the width of the fading function. It turned out that there are two different values of the width parameter used in literature: Veres and Chesley use 0.1 and Jones et al. (2018) use 0.12, following SDSS. Post-processing is currently using 0.1.

Currently, the chain to the width parameter is:

surveySimPP.py:140:        observations = PPFilterFadingFunction(observations, configs['fillfactor'], rng)
modules/PPFilterFadingFunction.py:27:    observations["detection_probability"] = PPDetectionProbability(observations, fillFactor=fillfactor)

modules/PPDetectionProbability.py:45:def calcDetectionProbability(mag, limmag, fillFactor=1.0, w=0.1):
calcDetectionProbability(oif_df[magnitude_name],oif_df[limiting_magnitude_name], fillFactor, w)
modules/PPDetectionProbability.py:94:            return calcDetectionProbability(oif_df[magnitude_name] + oif_df[trailing_loss_name],oif_df[limiting_magnitude_name], fillFactor, w)

So this would require:
1. adding a new parameter called 'fadingFunctionWidth' to the config file generator.
2. Make sure in the PPUtilities it is understood when read in.
3. Pass it as a parameter to PPFilterFadingFunction in surveySimPP.
4. Pass it as a parameter to  calcDetectionProbability in PPDetectionProbability.

**Comment by astronomerritt** [comment]
I can likely do this, although possibly not this week -- I need to fix the config file generator before the sprint.

**Comment by astronomerritt** [comment]
Quick question: I assume the width parameter is likely to be between 0 and 1? For error-handling :)
