### ISSUE TITLE
Should imports be in a separate file?

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#270]
Should imports be in a separate file? Would be good to see what other projects do

**Comment by mschwamb** [comment]
I am thinking we leave the imports in the file. Long is okay. People can scroll down to the rest of the code. It also makes it so it's not another file to open if you're trying to read through the code

**Comment by astronomerritt** [comment]
I'm fine with that. Hiding them looks tidier but you're right, it's adding unneeded complication.

Plus, [PEP20](https://peps.python.org/pep-0020/) says it's better to be explicit :)
