### ISSUE TITLE
Rename log files and interim database with process IDs as well as dates

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#303]
Although we recommend users send output of simultaneous instances to separate directories, this isn't enforced anywhere. The interim database and log/error files should thus get absolutely unique names so that no file conflicts occur: adding the process ID as well as the date and time should ensure this.

**Comment by mschwamb** [comment]
I think the process id is already there because the log and error files have:
2022-10-28-09-51-14-p31594-postprocessing.err
2022-10-26-10-07-14-p20029-postprocessing.log
