### ISSUE TITLE
PPDetectionProbability bug

### ISSUE THREAD

**Issue by cdbs** [dirac-institute/survey_simulator_post_processing#32]
running sample_recipe.py (for list of comets, with default parameters), generates following error

Traceback (most recent call last):
  File "sample_recipe.py", line 437, in <module>
    runPostProcessing()
  File "sample_recipe.py", line 358, in runPostProcessing
    observations=PPDetectionProbability.PPDetectionProbability(observations,limiting_magnitude)
AttributeError: 'function' object has no attribute 'PPDetectionProbability'

**Comment by fedorets** [comment]
I believe pull request #33 should solve the issue.
