### ISSUE TITLE
What happens if the user is only interested in one filter?

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#320]
I am pretty sure the code will break if the user only supplies one filter in 'observing_filters" and no colour offsets. I need to check that and fix it if so.

**Comment by mschwamb** [comment]
Good catch. This might be more tricky to fix. Given detection is in multiple filters because the nightly pairs are done mostly in separate filters, it might be something we don't worry about until v2.0 and just require there be at least filters specified for now

**Comment by mschwamb** [comment]
Depends on how easy a fix this is

**Comment by astronomerritt** [comment]
My initial instinct is that it should be a fairly easy fix. I might have a quick look at it, and if it gets more complicated than I thought, I can back-burner it.
