### ISSUE TITLE
Incorrect SQL query in documentation

### ISSUE THREAD

**Issue by drk98** [dirac-institute/survey_simulator_post_processing#322]
https://github.com/dirac-institute/survey_simulator_post_processing/blob/master/docs/configfiles.rst#L27

The query currently is:

  `SELECT observationId,observationStartMJD,fieldRA,fieldDEC,rotSkyPos FROM observations order by observationStartMJD`

It's missing `filter, seeingFwhmGeom, seeingFwhmEff, fiveSigmaDepth` so it should be 

  `SELECT observationId,observationStartMJD,fieldRA,fieldDEC,rotSkyPos,filter, seeingFwhmGeom, seeingFwhmEff, fiveSigmaDepth FROM observations order by observationStartMJD`

**Comment by mschwamb** [comment]
Thanks. I will update it
