### ISSUE TITLE
Linking filter checks and changes 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#340]
There is a  hardcoded number in Linking Filter. Looks like the start of the survey is hardcoded.

Check that a single night is set from 2pm to 2pm in Chile. 

Check with diffi  https://github.com/moeyensj/difi (or implement diffi) Diffi does missed linkages

**Comment by astronomerritt** [comment]
This is mostly complete - I'm currently waiting on difi implementation, at which point I will also add a toggle to turn precovery on and off and make the demo notebook.

**Comment by mschwamb** [comment]
Decision made to move to difi
