### ISSUE TITLE
Fix unintended behaviour when OIF column header missing

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#361]
An unusual bug has come up. If the OIF output file doesn't have column headings at all, the code will get stuck in an infinite loop as it repeatedly scans through the file looking for the column headings.

This is almost certainly due to the behaviour of PPSkipOifHeader (in PPReadOif.py), which I wrote to skip the large header OIF includes in its output files. I need to implement a fix that will cause it to stop after it's looked at the first ~100 lines and error out gracefully.

**Comment by mschwamb** [comment]
manually read in and confirm it has the start and end header lines as a double check I think
