### ISSUE TITLE
Broken test in docs

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/survey_simulator_post_processing#377]
In the installation docs under Testing the surveySimPP Installation[](https://survey-simulator-post-processing.readthedocs.io/en/latest/installation.html#testing-the-surveysimpp-installation) the following test is provided: 

`surveySimPP -c ./demo/PPConfig_test.ini -l ./demo/sspp_testset_colours.txt -o ./demo/sspp_testset_orbits.des -p ./demo/example_oif_output.txt -u ./data/out/ -t testrun_e2e`

It fails with message

`surveySimPP: error: the following arguments are required: -e/--ephem`

**Comment by astronomerritt** [comment]
Thanks for flagging this. For now, try:

`surveySimPP -c ./demo/PPConfig_test.ini -p ./demo/sspp_testset_colours.txt -o ./demo/sspp_testset_orbits.des -e ./demo/example_oif_output.txt -u ./data/out/ -t testrun_e2e`

**Comment by mschwamb** [comment]
Resolved in updated documentation for incubator
