### ISSUE TITLE
Config auxillary format keyword

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/survey_simulator_post_processing#378]
The config.ini file seems to be happy with auxiliary CSV format as long as it's designated with the "comma" keyword, but I get the error "ERROR: aux_format should be either comma, csv, or whitespace." when I provide the "csv" keyword, which is what I tried first since it's consistent with the ephemeris keyword. 

Updating that keyword to allow "csv" (or even not allow "comma" for consistency) would make more sense to me.

**Comment by astronomerritt** [comment]
Good spot. There's a pull request in now to fix this.
