### ISSUE TITLE
Discuss placement of 'demo' notebooks

### ISSUE THREAD

**Issue by drewoldag** [dirac-institute/survey_simulator_post_processing#402]
Once the LINCC Frameworks python project template is applied to SSPP, it will feature the ability to render Jupyter notebooks in the sphinx documentation (an example is here: https://qp-flexzboost.readthedocs.io/en/latest/notebooks.html) 

Question for the science team, do you all want to include the demo notebooks in the documentation?

**Comment by mschwamb** [comment]
Sure. They're examples demonstrating how the functions are working.

**Comment by drewoldag** [comment]
I'm going through the demo notebooks one by one just to confirm that they run, and have found a few that don't complete.  I could try digging into these, but I'm guessing that someone more familiar with the codebase will be able to move through the small issues much faster than I can. I'll create a separate issue for this: #410 

- demo_ApparentMagnitudeValidation.ipynb has a KeyError.
- demo_CircleFootprint.ipynb seems to take a while to run - there's a %%time annotation on one cell. Refactor if possible.
- demo_DetectionEfficiencyValidation.ipynb has a KeyError in the last cell
- demo_MagnitudeAndSNRCuts.ipynb has a KeyError
- demo_UncertaintyAndRandomization.ipynb has a KeyError

**Comment by mschwamb** [comment]
Can we make a label for the Seattle meeting and add this issue and #410 410 to it? Easy task for day 1.

**Comment by drewoldag** [comment]
In the notebook, `demo_UncertaintyAndRandomization.ipynb` the next to last cell produces an odd histogram that is perhaps indicative of a bug in the `randomizeAstronmetry` function. 

Note that there is a small bump well beyond -50000. 
<img width="646" alt="Screen Shot 2023-07-13 at 3 42 30 PM" src="https://github.com/dirac-institute/survey_simulator_post_processing/assets/47493171/18f67607-03f2-4737-a719-38d13ebcea61">

The last cell seems to produce a reasonable histogram.
<img width="646" alt="Screen Shot 2023-07-13 at 3 42 40 PM" src="https://github.com/dirac-institute/survey_simulator_post_processing/assets/47493171/8adf3eea-36c7-4af2-b392-988b53a43044">

**Comment by mschwamb** [comment]
My suggestion leave the notebooks until next week and go through them with Steph and Grigori directly together
