### ISSUE TITLE
Resolve duplication of continuous integration tests

### ISSUE THREAD

**Issue by drewoldag** [dirac-institute/survey_simulator_post_processing#405]
Now that the python project template is applied, there are multiple GitHub actions that run the same tests (pytest, codecov, linting) 

We should consolidate and remove unnecessary tests. As it stands, the ci.yml action seems to be the longest running set of checks. It runs against multiple versions of python as well as mac, windows and linux operating systems. 

We should settle on whether we need to support all of those operating systems and the agree upon which python versions we intend to support as well.

**Comment by drewoldag** [comment]
Science team, do you all have thoughts about which python versions and which operating systems need to be supported? For reference, LINCC Frameworks typically support python 3.8, 3.9, and 3.10 (and soon, 3.11 too). As far as operating systems, we've only been testing using GitHub's Ubuntu.

**Comment by mschwamb** [comment]
I think 3.8, 3.9, 3.10+ makes sense. I think that's what most astronomers are using right now. 

In terms of operating systems, most astronomers typically have linux or mac laptops. I think being bale to run on their laptop first before running a super computer would be an added bonus.  So if we can keep mac I would.  So I think being able to check mac eventually Mac silicon  (https://github.com/github/roadmap/issues/528) 

I think windows could go.  I think less than 1% of astronomers use windows.
