### ISSUE TITLE
PPLinkerFilter minimum date

### ISSUE THREAD

**Issue by jeremykubica** [dirac-institute/survey_simulator_post_processing#417]
PPLinkerFilter sets the first day as:

`first_day = observations.loc[0, "FieldMJD"]`

Which can lead to negative night labels when the first row contains a date later than the minimum. It might be clearer to use the minimum date over the entire data set, such as:

`first_day = np.min(observations['FieldMJD'].values)`

**Comment by mschwamb** [comment]
decision made to move to difi
