### ISSUE TITLE
Random Number Generator Updates

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#63]
- [ ]  Seed random number generator with computer time in seconds

- [ ]  Output seed to logfile

**Comment by fedorets** [comment]
I think there are situations where the seed needs to be repeated. Maybe this could be a parameter in the config file? For example, by default, seed is computer time. However, one can specify their own seed.

**Comment by astronomerritt** [comment]
I've checked the code and what `rng = np.random.default_rng(2021)` actually does is create a random number generator object, from which random numbers can later be pulled using various distributions. See the docs [here](https://numpy.org/doc/stable/reference/random/generator.html).

So it is actually creating different random numbers each time.

This does mean it's currently impossible to generate the exact same random numbers as a previous run, but looking at the code in PPRandomizeMeasurements, changing this could be a massive hassle, as it seems all of the functions were built around this generator object.

**Comment by mschwamb** [comment]
It's not when I try
>>> rng = np.random.default_rng(12345)
>>> arr1 = rng.random((3, 3))
>>> arr1
array([[0.22733602, 0.31675834, 0.79736546],
       [0.67625467, 0.39110955, 0.33281393],
       [0.59830875, 0.18673419, 0.67275604]])
>>> rng = np.random.default_rng(12345)
>>> arr1 = rng.random((3, 3))
>>> arr1
array([[0.22733602, 0.31675834, 0.79736546],
       [0.67625467, 0.39110955, 0.33281393],
       [0.59830875, 0.18673419, 0.67275604]])
>>>

**Comment by astronomerritt** [comment]
You're absolutely right -- I wasn't reinstantiating rng each time. Sorry! Will continue with fix.
