### ISSUE TITLE
Repeated data in observations and filterpointing

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#66]
Currently two main Pandas dataframes are created and used by the code: _observations_, which is the OIF input merged with the orbits/colour/comet input, and _filterpointing_, which is drawn from a few columns of the pointing database and contains all observations in the filters specified by the config file.

However, when PPCalculateApparentMagnitude is run, all of the information from _filterpointing_ is merged onto _observations_. This is fine, but it makes _filterpointing_ irrelevant, especially since _filterpointing_ contains _all_ observations of the specified filters, not just those which are actually contained in the OIF output.

I'm going to make a change to merge the relevant filters onto the _observations_ dataframe early on, but in the future it might be worth looking at merging the pointing database onto _observations_ early so that all functions which take _filterpointing_ as a variable instead work with the relevant columns in _observations_.

**Alternatively,** we could not merge _observations_ and _filterpointing_ at all, only adding filter info to _observations_ and otherwise keeping them separate. It's important that the relevant filter is in _observations_ so it's in the output, but the other information may be irrelevant. 

Computational load is also a question: is it easier to handle one Pandas dataframe with a few more columns or to split them up into two? Not sure on this myself.

Either way, the goal would be to minimise the amount of "repeated" data. Having the same data in both _observations_ and _filterpointing_ seems a waste of memory. Having information on **all** observations of the relevant filters in _filterpointing_, instead of just the ones that match up with the OIF input, seems a waste of memory.

**Comment by fedorets** [comment]
I think _filterpointing_ is needed at least as an intermediate step when reading from the pointing database. I wonder if one could purge the obsolete dataframe from memory when no longer needed? Something similar to Fortran's DEALLOCATE?

**Comment by fedorets** [comment]
For example, could something like 'del filterpointing' work?

**Comment by astronomerritt** [comment]
That's a great point. Python doesn't allow memory deallocation, it does its own background garbage collection and doesn't let us mere users interfere. So even if we delete the dataframe, we're reliant on Python's garbage collection freeing up the memory.

**Comment by fedorets** [comment]
Took a very quick read on this. It seems there is a module called gc which gives a manual way of triggering the garbage collection, albeit it is not recommended to use. Maybe worth clocking during load testing?

**Comment by astronomerritt** [comment]
Python does generally do a decent job of garbage collection, to be totally fair to it. 

But you're absolutely right that filterpointing is going to need to exist anyway, because obviously we have to read in the pointing database at some point, and it will need to stay in memory while the chunks are being looped through so that the code can continue to refer to it. (Doing any kind of merge before chunking seems like a _very bad idea_.) 

I hadn't factored this in previously and it does change my stance on the issue a bit! Apologies.

Anyway, I dug into the code a bit more and found something interesting...

Very relevantly, although PPDetectionProbability, PPTrailingLoss and PPVignetting.vignettingLosses take _filterpointing_ as an argument, **they don't actually use it**. They already read in the columns they need from _observations_. 

The only functions that actually use _filterpointing_ are PPCalculateApparentMagnitude, Footprint.applyFootprint and PPAddUncertainties.addUncertainties. And those latter two functions are actually doing a totally unnecessary **additional merge** between _observations_ and _filterpointing_ and then reading from that merged dataframe, even though that merge has already been performed within PPCalculateApparentMagnitude.

So I **think** the thing to do is to merge _filterpointing_ on observations at the start of the chunk (along with colours and orbits) so all the info we need is in the one dataframe, then rewrite the few functions that use _filterpointing_ to instead get their info from _observations_. 

I reckon I can easily do this myself for Footprint.applyFootprint and PPAddUncertainties.addUncertainties, so it would just a matter of taking the merge out of PPCalculateApparentMagnitude.

Hopefully this makes sense. My brain hurts.

**Comment by fedorets** [comment]
I forgot to write that in the pending pull request PPCalculateApparentMagnitude does no longer use filterpointing as an input parameter.

**Comment by mschwamb** [comment]
Check the latest pull request from Sam may have addressed part of this or all of this

**Comment by astronomerritt** [comment]
Partially. Issue #81 is still an issue: PPDetectionProbability, PPTrailingLoss and PPVignetting.vignettingLosses take _filterpointing_ as an argument, but don't actually use it within the function. I'm assigned to that, I can fix it.

While PPCalculateApparentMagnitude and PPAddUncertainies.addUncertainties now use only _observations_ as input, Footprint.applyFootprint is still taking _filterpointing_.
