### ISSUE TITLE
Duplicate object IDs in both colours/orbit input files

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#67]
If there is a duplicated object ID in both orbits and colours, and both objects have the same parameters, the code runs silently and completes, but with incorrect output. 

If there is a duplicated object ID in both orbits and colours, but the duplicate has _different_ parameters, then there's an ungraceful failure (KeyError, line 221 of surveySimPP.py, right after "INFO:root:Dropping observations with signal to noise ratio less than 2..."). 

If the duplicate object ID is only in one of these two input files, the code does detect a mismatch and fails gracefully. 

It's likely worth writing a separate utility to check files for duplicate object IDs, as this may be computationally-intensive.

**Comment by mschwamb** [comment]
I am wondering if this something that should be a stern warning rather than us to write a helper function. It's not a huge ask on the user to keep their ids unique

**Comment by astronomerritt** [comment]
I wouldn't argue with that. A helper function might be something that's nice to add down the line but I don't think it's a priority.

**Comment by mschwamb** [comment]
I'll add it to the documentation
