### ISSUE TITLE
PPMatchFieldConditions unnecessary?

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#70]
PPMatchFieldConditions (line 187) requeries the SQLite pointing database to pass out two Pandas dataframes, one of which (_limiting_magnitude_) isn't used in the code at all and the other (_seeing_) is used only once (line 202, calculation of trailing losses). 

All of the info in this _seeing_ dataframe is already in the _observations_ and _filterpointing_ dataframes at this point. PPMatchFieldConditions appears to be causing an unnecessary computational load. If PPTrailingLoss could be rewritten to pull the seeing info it needs from _observations_ or _filterpointing_, then PPMatchFieldConditions could be removed altogether.

**Comment by fedorets** [comment]
I agree with Steph's suggestion. I guess the limiting_magnitude frame predates the current way that the limiting magnitude is calculated.

**Comment by astronomerritt** [comment]
So PPTrailingLoss is actually referred to twice in surveySimPP.py.

On line 202, it takes _observations_ and _seeing_ as arguments. On line 230, it takes _observations_ and _filterpointing_.

PPTrailingLoss actually **uses** neither _seeing_ nor _filterpointing_. That argument is never referred to in the function.

So I think we can remove PPMatchFieldConditions altogether and eventually PPTrailingLoss will be rewritten to remove the redundant argument as per issue #81.

**Comment by fedorets** [comment]
PPTrailingLoss exists twice becayse it is present both in the camera and surface area footprints. It might be possible to leave only a single instance when rearranging things.

**Comment by astronomerritt** [comment]
Sorry, I wasn't clear!

It's fine that PPTrailingLoss is in there twice. I was pointing out that it takes _seeing_ as an argument in one instance and _filterpointing_ in the other. And in both cases, the function doesn't use either of these dataframes. 

So PPMatchFieldConditions can absolutely be removed. :)
