### ISSUE TITLE
Capture warnings in log

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#73]
I've checked and it looks like the logging module has functionality to capture any warnings the code outputs into a log, whether it's the existing logs or a separate one for warnings. 

Either way, triggered warnings should be logged somewhere, as most people won't be watching the code run so might miss them.

**Comment by mschwamb** [comment]
This may be of help https://alex-ber.medium.com/integrating-pythons-logging-and-warnings-packages-7ffd6f65e02d

**Comment by mschwamb** [comment]
Also this may help: https://stackoverflow.com/questions/38531786/capturewarnings-set-to-true-doesnt-capture-warnings

**Comment by astronomerritt** [comment]
Cool, thanks!

**Comment by mschwamb** [comment]
Don't need to do this anymore. The unit tests will fail if there's a warning.

**Comment by mschwamb** [comment]
See https://github.com/dirac-institute/survey_simulator_post_processing/pull/256
