### ISSUE TITLE
Verbose flag

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#74]
Add command-line flag and if statements for verbosity. 

At the moment the default should probably be verbose==True but we can flip this after testing.

Question: should verbose==False only suppress console output but maintain a log? Or should it also suppress logging for everything but errors/warnings?

**Comment by mschwamb** [comment]
All warnings should always go to the log file no matter the verbose setting

**Comment by astronomerritt** [comment]
Agreed, but what about non-error/warnings, i.e. the "info" logs? These are currently output to both the console and to the log file. Do we want the verbosity flag to suppress both logging and console output of non-vital info logging, or do we only suppress console output?

**Comment by fedorets** [comment]
So the initial idea for info-messages was to ensure everything is running smoothly for the new user. Once everything works, they shouldn't be needed by the heavy user :) So it should suppress the info messages going to the file.

However, all initial parameters which are read in from the config file should always be put into the log file, similar to oif and opsim.

**Comment by astronomerritt** [comment]
That makes a lot of sense! Users are then always able to discover what config parameters they used for a run even if all other info logging is suppressed. Got it, thanks!
