### ISSUE TITLE
Change output logfile name to include timestep/process id / other unique identifier

### ISSUE THREAD

**Issue by fedorets** [dirac-institute/survey_simulator_post_processing#79]
When multiple instances of code are ran, the postprocessing logfile contains only the output for the last run. A name of the postprocessing logfile should contain a unique identifier to prevent the overwriting.

Question: what could be the best unique identifier? Timesteps can coinside, and process id:s are not very informative -- perhaps a combination of both?

**Comment by astronomerritt** [comment]
I see what you mean: when the code's being run many times simultaneously, you could get identical timestamps. 

The other option might be to store the log files wherever the user specified as the output folder in the config file. Similarly, it could then be named using the outfile stem also specified in configs. However, this does of course rely on the user using different config files/output folders/outfile stems for their simultaneous runs.

**Comment by fedorets** [comment]
Thinking of user cases: if a user dispatches thousands of embarassingly parallel runs in SLURM using the config file generation utility, your suggestion could work since it is probably looped to give different input files. In that case the approach you are suggesting (with stems and folders) is probably the most appropriate one. Bit then there are cases where there aren't so many objects, adn people just run the code manually. In that case, there is a danger of overwriting by accident. Let's think what could be the most universal way.

**Comment by mschwamb** [comment]
Log files should be stored in the output folder which will help, I think adding a timestamp in the name would be helpful for the user long term. The code can look if a log file already exists with the same name and exit in an error if one already exists if there isn't a -f to overwrite everything. 

As already mentioned  if running multiple instances of the code at once you may hit the run condition where the log wasn't created from one instance when another one check for the presence of a log file,  no matter how much checking you have in place so I think at some point this become a user issue versus our issue. 

- [ ] log file written in output directory
- [ ] check if previous logfile exists with same name
- [ ] add timestamp to logfile name

**Comment by fedorets** [comment]
Having taken a look at this, there is a small chicken-egg problem here: the logger needs to be initialised before reading the config file where the output directory is given, so it can't be accessed. How about we shove all logs to a newly created log directory? An alternative is that the user will not know that we are reading the config file, but that may not necessarily be a major loss.

**Comment by mschwamb** [comment]
Decision is to add a time stamp and in the command line arguments add a variable for log directory

**Comment by fedorets** [comment]
In one of the previous pull requests Steph had already fixed the path issue. All that remained was adding dashes, seconds and the letter 'p' to the file name format.
