### ISSUE TITLE
remove main filter from config file read in and set from res filters

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#83]
The main filter is the first filter specified in the res filters string, but it also has to be set specifically as its own variable too in the config file.

 To minimize confusion and possibly having the two be different, the main filter config variable should be set by the first filter in the resfilters list.

**Comment by fedorets** [comment]
Maybe we should discuss this on Monday?

**Comment by fedorets** [comment]
Use the first one in the array of resfilters as mainfilter. Remove mainfilter from configfile to avoid mix-up.

**Comment by fedorets** [comment]
Fixed by pull request #129 .

**Comment by mschwamb** [comment]
Pull request not merged. Only merger should close tickets
