### ISSUE TITLE
converting object id to string should have in read in function not in suverysimpp

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#94]
```
 # comets may have dashes in their names that mix things up
        observations['ObjID'] = observations['ObjID'].astype(str)

```
Should be moved to the read in function for the observations file rather than in the main (surveysimpp) so it's clear this is associated with the readin and all functions downstream of readin are ensured to have the ObjID in the right format

**Comment by fedorets** [comment]
The best place for this is probably the PPCheckOrbitAndColourMatching function where all ObjID:s are tested against one another.

**Comment by fedorets** [comment]
The line will be moved to all four read-in functions.

**Comment by fedorets** [comment]
Fixid in pulled request #98.
