### ISSUE TITLE
other minor tasks 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#95]
- [ ] Make PPReadEphemerides module-- encapsulate PPReadOif in PPReadEphemerides  so in the future in would not be hard to write a function reading in a different format
- [ ] Clarify inside PPcalculateApparentMagnitudes. One of the functions should be called  PPApplyColourOffset
- [ ] Implement removing temporary database as its own flag

**Comment by fedorets** [comment]
Fixed in pull request #100.
