### ISSUE TITLE
Should we change post processing config file variable for sql query so it has the same name as objects in field?

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#96]
Objects in field has Surveydbquery for the rubin_sim output query string and in post processing we're using ppsqldbquery in the post processing config file variable for the same thing. 

Is that confusing that we're using different variable names in the configs for for this? Should we make them consistent?

**Comment by fedorets** [comment]
I think making them different avoids them being mixed up when dealing with the different scripts. At least that was my initial idea.

**Comment by mschwamb** [comment]
That's a fair point.
